version: '3.3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6543:5432
  web:
    build:
      context: .
    command: gunicorn SnowManAPI.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    ports:
      - 8000:8000