# Generated by Django 3.0.8 on 2020-07-28 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20200721_2221'), ('core', '0003_auto_20200722_0013'), ('core', '0004_auto_20200723_1107'), ('core', '0005_auto_20200723_1130'), ('core', '0006_auto_20200723_1146'), ('core', '0007_auto_20200724_1701'), ('core', '0008_auto_20200727_1657'), ('core', '0009_auto_20200728_1114')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TbCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TbPicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TbTouristSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('geo_location', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.TbCategory')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.TbPicture')),
            ],
        ),
        migrations.CreateModel(
            name='TbUserFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tourist_spot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.TbTouristSpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tbpicture',
            name='tourist_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.TbTouristSpot'),
        ),
        migrations.AlterModelTable(
            name='tbcategory',
            table='TB_CATEGORY',
        ),
        migrations.AlterModelTable(
            name='tbpicture',
            table='TB_PICTURE',
        ),
        migrations.AlterModelTable(
            name='tbtouristspot',
            table='TB_TOURIST_SPOT',
        ),
        migrations.AlterModelTable(
            name='tbuserfavorite',
            table='TB_USER_FAVORITE',
        ),
        migrations.RemoveField(
            model_name='tbpicture',
            name='tourist_spot',
        ),
        migrations.RemoveField(
            model_name='tbtouristspot',
            name='picture',
        ),
        migrations.AddField(
            model_name='tbpicture',
            name='tourist_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core.TbTouristSpot'),
        ),
        migrations.AlterField(
            model_name='tbuserfavorite',
            name='tourist_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TbTouristSpot'),
        ),
        migrations.AlterField(
            model_name='tbuserfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tbuserfavorite',
            unique_together={('user', 'tourist_spot')},
        ),
        migrations.RemoveField(
            model_name='tbtouristspot',
            name='geo_location',
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='lat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='long',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbtouristspot',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
