# Generated by Django 3.0.8 on 2020-07-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200721_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbpicture',
            name='tourist_spot',
        ),
        migrations.RemoveField(
            model_name='tbtouristspot',
            name='picture',
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='pictures',
            field=models.ManyToManyField(to='core.TbPicture'),
        ),
    ]
