# Generated by Django 3.0.8 on 2020-07-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200723_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbpicture',
            name='tourist_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='core.TbTouristSpot'),
        ),
    ]
