# Generated by Django 3.0.8 on 2020-07-24 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200723_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbpicture',
            name='tourist_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core.TbTouristSpot'),
        ),
        migrations.AlterField(
            model_name='tbuserfavorite',
            name='tourist_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TbTouristSpot'),
        ),
        migrations.AlterField(
            model_name='tbuserfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tbuserfavorite',
            unique_together={('user', 'tourist_spot')},
        ),
    ]
