# Generated by Django 3.0.8 on 2020-07-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200724_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbtouristspot',
            name='geo_location',
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='lat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='long',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbtouristspot',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
