# Generated by Django 3.0.8 on 2020-07-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200727_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbtouristspot',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
